title: Hi!<br>I'm Jonathan Kim
logo: /assets/profilepic.jpeg
show_downloads: true
theme: jekyll-theme-minimal
My Resume: /assets/Jonathan Kim's Embedded and Firmware Resume.pdf
email: Jonathankim829@email.com
phone: "+1-909-657-6129"
github_username: ScoobyXD
linkedin_username: www.linkedin.com/in/jonathankim829
